GitOS: src/kernel/fs/memory/MemoryFS.cpp File Reference
MemoryFS.cpp File Reference
#include "MemoryFS.hpp"
#include <common/assert.h>
#include <common/status.h>
#include <memory/memory.h>
Functions
int memory_close (void *data)
void * memory_open (void *data, struct path_part *path, FILE_MODE mode)
int memory_read (void *private_fs, void *desc, uint32_t size, uint32_t nmemb, char *out)
int memory_write (void *private_fs, void *desc, uint32_t size, uint32_t nmemb, char *in)
int memory_seek (void *desc, uint32_t offset, FILE_SEEK_MODE seek_mode)
int memory_stat (void *desc, file_stat *stat)
int memory_resolve (struct disk *disk)
Function Documentation
memory_close()
int memory_close (void * data)
References assert_not_reached.
memory_open()
void * memory_open (void * data, struct path_part * path, FILE_MODE mode)
memory_read()
int memory_read (void * private_fs, void * desc, uint32_t size, uint32_t nmemb, char * out)
References fs, MemoryFS::read(), and size.
memory_resolve()
int memory_resolve (struct disk * disk)
memory_seek()
int memory_seek (void * desc, uint32_t offset, FILE_SEEK_MODE seek_mode)
References fs, offset, and MemoryFS::seek().
memory_stat()
int memory_stat (void * desc, file_stat * stat)
References FILE_MODE_APPEND, FILE_MODE_READ, FILE_MODE_WRITE, file_stat::filesize, file_stat::flags, and fs.
memory_write()
int memory_write (void * private_fs, void * desc, uint32_t size, uint32_t nmemb, char * in)
References fs, size, and MemoryFS::write().