var annotated_dup =
[
    [ "disk", "structdisk.html", "structdisk" ],
    [ "disk_stream", "structdisk__stream.html", "structdisk__stream" ],
    [ "ELFFile", "class_e_l_f_file.html", "class_e_l_f_file" ],
    [ "fat16_header_extended", "structfat16__header__extended.html", "structfat16__header__extended" ],
    [ "fat16_header_primary", "structfat16__header__primary.html", "structfat16__header__primary" ],
    [ "fat_directory", "structfat__directory.html", "structfat__directory" ],
    [ "fat_file", "structfat__file.html", "structfat__file" ],
    [ "fat_file_descriptor", "structfat__file__descriptor.html", "structfat__file__descriptor" ],
    [ "fat_header", "structfat__header.html", "structfat__header" ],
    [ "fat_item", "structfat__item.html", "structfat__item" ],
    [ "fat_private", "structfat__private.html", "structfat__private" ],
    [ "file_descriptor", "structfile__descriptor.html", "structfile__descriptor" ],
    [ "file_stat", "structfile__stat.html", "structfile__stat" ],
    [ "filesystem", "structfilesystem.html", "structfilesystem" ],
    [ "gdt", "structgdt.html", "structgdt" ],
    [ "gdt_descriptor", "structgdt__descriptor.html", "structgdt__descriptor" ],
    [ "gdt_structured", "structgdt__structured.html", "structgdt__structured" ],
    [ "Graphics", "class_graphics.html", "class_graphics" ],
    [ "heap", "structheap.html", "structheap" ],
    [ "heap_table", "structheap__table.html", "structheap__table" ],
    [ "idt_desc", "structidt__desc.html", "structidt__desc" ],
    [ "idtr_desc", "structidtr__desc.html", "structidtr__desc" ],
    [ "interrupt_frame", "structinterrupt__frame.html", "structinterrupt__frame" ],
    [ "paging_chunk", "structpaging__chunk.html", "structpaging__chunk" ],
    [ "path_part", "structpath__part.html", "structpath__part" ],
    [ "path_root", "structpath__root.html", "structpath__root" ],
    [ "process", "structprocess.html", "structprocess" ],
    [ "registers", "structregisters.html", "structregisters" ],
    [ "task", "structtask.html", "structtask" ],
    [ "TextModeGraphics", "class_text_mode_graphics.html", "class_text_mode_graphics" ],
    [ "tss", "structtss.html", "structtss" ],
    [ "VBEGraphics", "class_v_b_e_graphics.html", "class_v_b_e_graphics" ]
];