GitOS: VBEGraphics Class Reference
VBEGraphics Class Reference
#include <vbe_graphics.hpp>
Inherits Graphics.
Public Member Functions
virtual void draw_pixel (uint32_t x, uint32_t y, uint32_t color)
virtual void draw_char (uint32_t x, uint32_t y, char c, uint32_t color)
virtual void draw_string (uint32_t x, uint32_t y, const char *str, uint32_t color)
virtual void print_char (char c)
virtual void print_char_color (char c, TEXT_MODE_COLOR color)
virtual void print_string (const char *str)
virtual void print_string_color (const char *str, TEXT_MODE_COLOR color)
virtual void clear_screen ()
virtual void set_cursor (uint32_t x, uint32_t y)
virtual uint32_t get_cursor_x ()
virtual uint32_t get_cursor_y ()
virtual TEXT_MODE_COLOR get_current_color ()
virtual void set_text_color (TEXT_MODE_COLOR color)
void scroll_screen (int i)
bool is_vbe () const
uint32_t get_rrggbb_color (TEXT_MODE_COLOR color)
uint32_t get_framebuffer_size () const
uint32_t get_bpp () const
uint32_t get_height () const
uint32_t get_width () const
uint8_t * get_framebuffer () const
void setup (uint8_t *framebuffer, uint32_t bpp, uint32_t width, uint32_t height)
void mount_fb ()
Public Member Functions inherited from Graphics
virtual ~Graphics ()=default
Static Public Member Functions
static Graphics * the ()
Static Public Member Functions inherited from Graphics
static Graphics * the ()
Additional Inherited Members
Public Types inherited from Graphics
enum TEXT_MODE_COLOR {
BLACK , BLUE , GREEN , CYAN ,
RED , PURPLE , BROWN , GREY ,
DARK_GREY , LIGHT_BLUE , LIGHT_GREEN , LIGHT_CYAN ,
LIGHT_RED , LIGHT_PURPLE , YELLOW , WHITE
}
Member Function Documentation
clear_screen()
void clear_screen () virtual
Implements Graphics.
References draw_pixel().
draw_char()
void draw_char (uint32_t x, uint32_t y, char c, uint32_t color) virtual
References draw_pixel().
draw_pixel()
void draw_pixel (uint32_t x, uint32_t y, uint32_t color) virtual
References offset.
draw_string()
void draw_string (uint32_t x, uint32_t y, const char * str, uint32_t color) virtual
References draw_char().
get_bpp()
uint32_t get_bpp () const
get_current_color()
Graphics::TEXT_MODE_COLOR get_current_color () virtual
Implements Graphics.
get_cursor_x()
uint32_t get_cursor_x () virtual
Implements Graphics.
get_cursor_y()
uint32_t get_cursor_y () virtual
Implements Graphics.
get_framebuffer()
uint8_t * get_framebuffer () const
get_framebuffer_size()
size_t get_framebuffer_size () const
get_height()
uint32_t get_height () const
get_rrggbb_color()
uint32_t get_rrggbb_color (TEXT_MODE_COLOR color)
References Graphics::BLACK, Graphics::BLUE, Graphics::BROWN, Graphics::CYAN, Graphics::DARK_GREY, Graphics::GREEN, Graphics::GREY, Graphics::LIGHT_BLUE, Graphics::LIGHT_CYAN, Graphics::LIGHT_GREEN, Graphics::LIGHT_PURPLE, Graphics::LIGHT_RED, Graphics::PURPLE, Graphics::RED, Graphics::WHITE, and Graphics::YELLOW.
get_width()
uint32_t get_width () const
is_vbe()
bool is_vbe () const
mount_fb()
void mount_fb ()
References get_framebuffer_size(), MemoryFS::get_struct(), and mount().
print_char()
void print_char (char c) virtual
Implements Graphics.
References print_char_color().
print_char_color()
void print_char_color (char c, TEXT_MODE_COLOR color) virtual
Implements Graphics.
References draw_char(), get_rrggbb_color(), and scroll_screen().
print_string()
void print_string (const char * str) virtual
Implements Graphics.
References print_string_color().
print_string_color()
void print_string_color (const char * str, TEXT_MODE_COLOR color) virtual
Implements Graphics.
References print_char_color().
scroll_screen()
void scroll_screen (int i)
References memcpy(), and memset().
set_cursor()
void set_cursor (uint32_t x, uint32_t y) virtual
Implements Graphics.
set_text_color()
void set_text_color (TEXT_MODE_COLOR color) virtual
Implements Graphics.
setup()
void setup (uint8_t * framebuffer, uint32_t bpp, uint32_t width, uint32_t height)
References bpp, framebuffer, height, kprintf(), and width.
the()
Graphics * the () static
The documentation for this class was generated from the following files:
src/kernel/drivers/graphics/vbe/vbe_graphics.hpp
src/kernel/drivers/graphics/vbe/vbe_graphics.cpp