GitOS: Graphics Class Reference
Graphics Class Reference
#include <graphics.hpp>
Public Member Functions
void draw_pixel (uint32_t x, uint32_t y, uint32_t color)
void draw_char (uint32_t x, uint32_t y, char c, uint32_t color)
void draw_string (uint32_t x, uint32_t y, const char *str, uint32_t color)
void print_char (char c, uint32_t color)
void print_string (const char *str, uint32_t color)
void print_vbe_mode_info () const
Static Public Member Functions
static Graphics * the ()
Member Function Documentation
draw_char()
void draw_char (uint32_t x, uint32_t y, char c, uint32_t color)
References draw_pixel().
draw_pixel()
void draw_pixel (uint32_t x, uint32_t y, uint32_t color)
draw_string()
void draw_string (uint32_t x, uint32_t y, const char * str, uint32_t color)
References draw_char().
print_char()
void print_char (char c, uint32_t color)
References draw_char().
print_string()
void print_string (const char * str, uint32_t color)
References print_char().
print_vbe_mode_info()
void print_vbe_mode_info () const
References attributes, banks, bankSize, blueMask, bluePosition, bpp, directColorAttributes, framebuffer, granularity, greenMask, greenPosition, imagePages, memoryModel, offScreenMemOffset, offScreenMemSize, pitch, planes, realFctPtr, redMask, redPosition, reserved0, reserved1, reservedMask, reservedPosition, segmentA, segmentB, winA, winB, winSize, xCharSize, xRes, yCharSize, and yRes.
the()
Graphics * the () static
The documentation for this class was generated from the following files:
src/kernel/drivers/graphics/graphics.hpp
src/kernel/drivers/graphics/graphics.cpp