GitOS: MemoryFS Class Reference
MemoryFS Class Reference
#include <MemoryFS.hpp>
Public Member Functions
MemoryFS (char *buffer, size_t buffer_size)
filesystem * get_struct ()
uint32_t get_buffer_size ()
int read (uint32_t size, char *out)
int write (char *data, uint32_t size)
int seek (uint32_t offset, FILE_SEEK_MODE seek_mode)
Constructor & Destructor Documentation
MemoryFS()
MemoryFS (char * buffer, size_t buffer_size)
Member Function Documentation
get_buffer_size()
uint32_t get_buffer_size ()
get_struct()
filesystem * get_struct ()
References fs, memory_close(), memory_open(), memory_read(), memory_resolve(), memory_seek(), memory_stat(), memory_write(), and filesystem::resolve.
read()
int read (uint32_t size, char * out)
References EINVARG, memcpy(), and size.
seek()
int seek (uint32_t offset, FILE_SEEK_MODE seek_mode)
References ALL_OK, EINVARG, offset, SEEK_CUR, SEEK_END, and SEEK_SET.
write()
int write (char * data, uint32_t size)
References data, EINVARG, memcpy(), and size.
The documentation for this class was generated from the following files:
src/kernel/fs/memory/MemoryFS.hpp
src/kernel/fs/memory/MemoryFS.cpp