GitOS: PipeFS Class Reference
PipeFS Class Reference
#include <PipeFS.hpp>
Public Member Functions
PipeFS (size_t buffer_size)
filesystem * get_struct ()
uint32_t get_buffer_size ()
int read (uint32_t size, char *out)
int write (const char *data, uint32_t size)
Constructor & Destructor Documentation
PipeFS()
PipeFS (size_t buffer_size)
References kzalloc().
Member Function Documentation
get_buffer_size()
uint32_t get_buffer_size ()
get_struct()
filesystem * get_struct ()
References fs, pipe_close(), pipe_open(), pipe_read(), pipe_resolve(), pipe_seek(), pipe_stat(), pipe_write(), and filesystem::resolve.
read()
int read (uint32_t size, char * out)
References memcpy(), and size.
write()
int write (const char * data, uint32_t size)
References data, memcpy(), and size.
The documentation for this class was generated from the following files:
src/kernel/fs/pipe/PipeFS.hpp
src/kernel/fs/pipe/PipeFS.cpp