GitOS: ELFFile Class Reference
ELFFile Class Reference
#include <ELFFile.hpp>
Public Types
typedef uint16_t Elf32_Half
typedef uint32_t Elf32_Word
typedef int32_t Elf32_Sword
typedef uint32_t Elf32_Addr
typedef int32_t Elf32_Off
Public Member Functions
bool is_valid () const
ELFFile (void *data, size_t size)
~ELFFile ()
int parse ()
void * get_physical_base_address () const
void * get_physical_end_address () const
void * get_virtual_base_address () const
void * get_virtual_end_address () const
void * get_entry () const
struct __attribute__ ((__packed__))
struct __attribute__ ((__packed__))
struct __attribute__ ((__packed__))
struct __attribute__ ((__packed__))
struct __attribute__ ((__packed__))
Elf32_Header * get_header () const
Elf32_Phdr * get_program_header () const
Elf32_Phdr * get_program_header (unsigned int index) const
Elf32_Shdr * get_section_header () const
Elf32_Shdr * get_section_header (unsigned int index) const
const char * get_string_table () const
Data Fields
Elf32_Phdr
Elf32_Shdr
Elf32_Header
Elf32_Dyn
Elf32_Sym
Static Public Attributes
static constexpr char ELF_SIGNATURE [] = {0x7f, 'E', 'L', 'F'}
static const unsigned int PF_X = 1
static const unsigned int PF_R = 4
static const unsigned int PF_W = 2
static const unsigned int PT_NULL = 0
static const unsigned int PT_LOAD = 1
static const unsigned int PT_DYNAMIC = 2
static const unsigned int PT_INTERP = 3
static const unsigned int PT_NOTE = 4
static const unsigned int PT_SHLIB = 5
static const unsigned int PT_PHDR = 6
static const unsigned int SHT_NULL = 0
static const unsigned int SHT_PROGBITS = 1
static const unsigned int SHT_SYMTAB = 2
static const unsigned int SHT_STRTAB = 3
static const unsigned int SHT_RELA = 4
static const unsigned int SHT_HASH = 5
static const unsigned int SHT_DYNAMIC = 6
static const unsigned int SHT_NOTE = 7
static const unsigned int SHT_NOBITS = 8
static const unsigned int SHT_REL = 9
static const unsigned int SHT_SHLIB = 10
static const unsigned int SHT_DYNSYM = 11
static const unsigned int SHT_LOPROC = 12
static const unsigned int SHT_HIPROC = 13
static const unsigned int SHT_LOUSER = 14
static const unsigned int SHT_HIUSER = 15
static const unsigned int ET_NONE = 0
static const unsigned int ET_REL = 1
static const unsigned int ET_EXEC = 2
static const unsigned int ET_DYN = 3
static const unsigned int ET_CORE = 4
static const unsigned int EI_NIDENT = 16
static const unsigned int EI_CLASS = 4
static const unsigned int EI_DATA = 5
static const unsigned int ELFCLASSNONE = 0
static const unsigned int ELFCLASS32 = 1
static const unsigned int ELFCLASS64 = 2
static const unsigned int ELFDATANONE = 0
static const unsigned int ELFDATA2LSB = 1
static const unsigned int ELFDATA2MSB = 2
static const unsigned int SHN_UNDEF = 0
Member Typedef Documentation
Elf32_Addr
typedef uint32_t Elf32_Addr
Elf32_Half
typedef uint16_t Elf32_Half
Elf32_Off
typedef int32_t Elf32_Off
Elf32_Sword
typedef int32_t Elf32_Sword
Elf32_Word
typedef uint32_t Elf32_Word
Constructor & Destructor Documentation
ELFFile()
ELFFile (void * data, size_t size)
References size.
~ELFFile()
~ELFFile ()
References kfree().
Member Function Documentation
__attribute__() [1/5]
struct __attribute__ ((__packed__)) inline
__attribute__() [2/5]
struct __attribute__ ((__packed__)) inline
__attribute__() [3/5]
struct __attribute__ ((__packed__)) inline
__attribute__() [4/5]
struct __attribute__ ((__packed__)) inline
__attribute__() [5/5]
struct __attribute__ ((__packed__)) inline
get_entry()
void * get_entry () const
References get_header().
get_header()
ELFFile::Elf32_Header * get_header () const
References Elf32_Header.
get_physical_base_address()
void * get_physical_base_address () const
get_physical_end_address()
void * get_physical_end_address () const
get_program_header() [1/2]
ELFFile::Elf32_Phdr * get_program_header () const
References Elf32_Phdr, and get_header().
get_program_header() [2/2]
ELFFile::Elf32_Phdr * get_program_header (unsigned int index) const
References get_program_header().
get_section_header() [1/2]
ELFFile::Elf32_Shdr * get_section_header () const
References Elf32_Shdr, and get_header().
get_section_header() [2/2]
ELFFile::Elf32_Shdr * get_section_header (unsigned int index) const
References get_section_header().
get_string_table()
const char * get_string_table () const
References get_header(), and get_section_header().
get_virtual_base_address()
void * get_virtual_base_address () const
get_virtual_end_address()
void * get_virtual_end_address () const
is_valid()
bool is_valid () const
References EI_CLASS, EI_DATA, Elf32_Header, ELF_SIGNATURE, ELFCLASS32, ELFDATA2LSB, ET_EXEC, memcmp(), and PROGRAM_VIRTUAL_ADDRESS.
parse()
int parse ()
References EINFORMAT, get_header(), get_program_header(), is_valid(), and PT_LOAD.
Field Documentation
EI_CLASS
const unsigned int EI_CLASS = 4 static
EI_DATA
const unsigned int EI_DATA = 5 static
EI_NIDENT
const unsigned int EI_NIDENT = 16 static
Elf32_Dyn
Elf32_Dyn
Elf32_Header
Elf32_Header
Elf32_Phdr
Elf32_Phdr
Elf32_Shdr
Elf32_Shdr
Elf32_Sym
Elf32_Sym
ELF_SIGNATURE
constexpr char ELF_SIGNATURE[] = {0x7f, 'E', 'L', 'F'} static constexpr
ELFCLASS32
const unsigned int ELFCLASS32 = 1 static
ELFCLASS64
const unsigned int ELFCLASS64 = 2 static
ELFCLASSNONE
const unsigned int ELFCLASSNONE = 0 static
ELFDATA2LSB
const unsigned int ELFDATA2LSB = 1 static
ELFDATA2MSB
const unsigned int ELFDATA2MSB = 2 static
ELFDATANONE
const unsigned int ELFDATANONE = 0 static
ET_CORE
const unsigned int ET_CORE = 4 static
ET_DYN
const unsigned int ET_DYN = 3 static
ET_EXEC
const unsigned int ET_EXEC = 2 static
ET_NONE
const unsigned int ET_NONE = 0 static
ET_REL
const unsigned int ET_REL = 1 static
PF_R
const unsigned int PF_R = 4 static
PF_W
const unsigned int PF_W = 2 static
PF_X
const unsigned int PF_X = 1 static
PT_DYNAMIC
const unsigned int PT_DYNAMIC = 2 static
PT_INTERP
const unsigned int PT_INTERP = 3 static
PT_LOAD
const unsigned int PT_LOAD = 1 static
PT_NOTE
const unsigned int PT_NOTE = 4 static
PT_NULL
const unsigned int PT_NULL = 0 static
PT_PHDR
const unsigned int PT_PHDR = 6 static
PT_SHLIB
const unsigned int PT_SHLIB = 5 static
SHN_UNDEF
const unsigned int SHN_UNDEF = 0 static
SHT_DYNAMIC
const unsigned int SHT_DYNAMIC = 6 static
SHT_DYNSYM
const unsigned int SHT_DYNSYM = 11 static
SHT_HASH
const unsigned int SHT_HASH = 5 static
SHT_HIPROC
const unsigned int SHT_HIPROC = 13 static
SHT_HIUSER
const unsigned int SHT_HIUSER = 15 static
SHT_LOPROC
const unsigned int SHT_LOPROC = 12 static
SHT_LOUSER
const unsigned int SHT_LOUSER = 14 static
SHT_NOBITS
const unsigned int SHT_NOBITS = 8 static
SHT_NOTE
const unsigned int SHT_NOTE = 7 static
SHT_NULL
const unsigned int SHT_NULL = 0 static
SHT_PROGBITS
const unsigned int SHT_PROGBITS = 1 static
SHT_REL
const unsigned int SHT_REL = 9 static
SHT_RELA
const unsigned int SHT_RELA = 4 static
SHT_SHLIB
const unsigned int SHT_SHLIB = 10 static
SHT_STRTAB
const unsigned int SHT_STRTAB = 3 static
SHT_SYMTAB
const unsigned int SHT_SYMTAB = 2 static
The documentation for this class was generated from the following files:
src/kernel/formats/elf/ELFFile.hpp
src/kernel/formats/elf/ELFFile.cpp