GitOS: PS2Mouse Class Reference
PS2Mouse Class Reference
#include <PS2Mouse.hpp>
Public Member Functions
void handle_cycle ()
void wait (uint8_t type) const
void write (uint8_t byte) const
uint8_t read () const
Static Public Member Functions
static PS2Mouse * instance ()
Member Function Documentation
handle_cycle()
void handle_cycle ()
References inb(), Compositor::instance(), pic_EOI(), and Compositor::push_mouse().
instance()
PS2Mouse * instance () static
References instance().
read()
uint8_t read () const
References inb(), and wait().
wait()
void wait (uint8_t type) const inline
References inb(), and kprintf().
write()
void write (uint8_t byte) const inline
References outb(), and wait().
The documentation for this class was generated from the following files:
src/kernel/drivers/ps2mouse/PS2Mouse.hpp
src/kernel/drivers/ps2mouse/PS2Mouse.cpp