GitOS: src/userland/stdlib/crt0.c File Reference
crt0.c File Reference
#include "misc.h"
Functions
int main (int argc, char **argv)
void crt0 ()
Function Documentation
crt0()
void crt0 ()
References exit(), get_process_arguments(), and main().
main()
int main (int argc, char ** argv) extern
References CLOSE, data, debug_printf(), window::dirty, execprocess(), window::fd, window::finished_moving, fopen(), FRAMEBUFFER_DATA, fread(), free(), fseek(), fstat(), fwrite(), get_cwd(), getc(), window::height, malloc(), memcmp(), memcpy(), memset(), window::moving, window::name, window::old_x, window::old_y, open_ipc(), printf(), process_command(), putc(), REGISTER, SEEK_SET, SET_SIZE, FramebufferGraphics::the(), window::width, window::x, and window::y.