GitOS: src/kernel/drivers/disk/disk_streamer.h File Reference
disk_streamer.h File Reference
Data Structures
struct disk_stream
Functions
int diskstreamer_read (struct disk_stream *stream, void *out, int total)
Reads specified amount of bytes into buffer.
int diskstreamer_seek (struct disk_stream *stream, int pos)
Seeks into specified offset in stream.
struct disk_stream * diskstreamer_new (int disk_id)
Allocates and sets up new disk_stream struct.
void diskstreamer_close (struct disk_stream *stream)
Frees allocated disk_stream.
Function Documentation
diskstreamer_close()
void diskstreamer_close (struct disk_stream * stream)
Frees allocated disk_stream.
Parameters
stream Stream to close
References kfree().
diskstreamer_new()
struct disk_stream* diskstreamer_new (int disk_id)
Allocates and sets up new disk_stream struct.
Parameters
disk_id Disk ID
Returns
struct disk_stream* Created struct
References disk_stream::disk, disk_get(), kzalloc(), and disk_stream::pos.
diskstreamer_read()
int diskstreamer_read (struct disk_stream * stream, void * out, int total)
Reads specified amount of bytes into buffer.
Parameters
stream Stream to read
out Target buffer
total Total amount of bytes to read
Returns
int Status
References disk_stream::disk, disk_read_block(), DISK_SECTOR_SIZE, diskstreamer_read(), and disk_stream::pos.
diskstreamer_seek()
int diskstreamer_seek (struct disk_stream * stream, int pos)
Seeks into specified offset in stream.
Parameters
stream Stream to seek
pos Bytes from 0
Returns
int 0
References disk_stream::pos.