GitOS: src/kernel/fs/fat16/fat16.c File Reference
fat16.c File Reference
#include "fat16.h"
#include "common/string.h"
#include "common/status.h"
#include "memory/memory.h"
#include "memory/heap/kheap.h"
#include "kernel.h"
Functions
struct filesystem * fat16_init ()
int fat16_init_private (struct disk *disk, struct fat_private *private)
void fat16_free_private (struct fat_private *private)
void fat16_get_full_relative_filename (struct fat_directory_item *item, char *out, int max_len)
void fat16_free_directory (struct fat_directory *directory)
void fat16_fat_item_free (struct fat_item *item)
struct fat_directory * fat16_load_fat_directory (struct disk *disk, struct fat_directory_item *item)
struct fat_item * fat16_new_fat_item_for_directory_item (struct disk *disk, struct fat_directory_item *item)
struct fat_item * fat16_find_item_in_directory (struct disk *disk, struct fat_directory *directory, const char *name)
struct fat_item * fat16_get_directory_entry (struct disk *disk, struct path_part *path)
void * fat16_open (struct disk *disk, struct path_part *path, FILE_MODE mode)
int fat16_resolve (struct disk *disk)
int fat16_read (struct disk *disk, void *descriptor_buffer, uint32_t size, uint32_t nmemb, char *out)
Variables
struct filesystem fat16_fs
Function Documentation
fat16_fat_item_free()
void fat16_fat_item_free (struct fat_item * item)
References fat_item::directory, fat16_free_directory(), FAT_ITEM_TYPE_DIRECTORY, FAT_ITEM_TYPE_FILE, fat_item::item, kernel_panic(), kfree(), and fat_item::type.
fat16_find_item_in_directory()
struct fat_item* fat16_find_item_in_directory (struct disk * disk, struct fat_directory * directory, const char * name)
References fat_item::directory, fat16_get_full_relative_filename(), fat16_new_fat_item_for_directory_item(), istrncmp(), fat_directory::item, MAX_PATH, and fat_directory::total.
fat16_free_directory()
void fat16_free_directory (struct fat_directory * directory)
References fat_directory::item, and kfree().
fat16_free_private()
void fat16_free_private (struct fat_private * private)
References diskstreamer_close(), and kfree().
fat16_get_directory_entry()
struct fat_item* fat16_get_directory_entry (struct disk * disk, struct path_part * path)
References fat_item::directory, fat16_fat_item_free(), fat16_find_item_in_directory(), FAT_ITEM_TYPE_DIRECTORY, disk::fs_private, path_part::next, path_part::part, and fat_private::root_directory.
fat16_get_full_relative_filename()
void fat16_get_full_relative_filename (struct fat_directory_item * item, char * out, int max_len)
References memset().
fat16_init()
struct filesystem* fat16_init ()
References fat16_fs, filesystem::name, and strcpy().
fat16_init_private()
int fat16_init_private (struct disk * disk, struct fat_private * private)
References ALL_OK, diskstreamer_new(), disk::id, and memset().
fat16_load_fat_directory()
struct fat_directory* fat16_load_fat_directory (struct disk * disk, struct fat_directory_item * item)
References fat_directory_item::attribute, EIO, ENOMEM, FAT_FILE_SUBDIRECTORY, disk::fs_private, and kzalloc().
fat16_new_fat_item_for_directory_item()
struct fat_item* fat16_new_fat_item_for_directory_item (struct disk * disk, struct fat_directory_item * item)
References fat_directory_item::attribute, fat_item::directory, fat16_load_fat_directory(), FAT_FILE_SUBDIRECTORY, FAT_ITEM_TYPE_DIRECTORY, FAT_ITEM_TYPE_FILE, fat_item::item, kzalloc(), and fat_item::type.
fat16_open()
void* fat16_open (struct disk * disk, struct path_part * path, FILE_MODE mode)
References BochsBreak, EINVARG, EIO, ENOMEM, fat16_get_directory_entry(), FILE_MODE_READ, fat_file_descriptor::item, kzalloc(), and fat_file_descriptor::pos.
fat16_read()
int fat16_read (struct disk * disk, void * descriptor_buffer, uint32_t size, uint32_t nmemb, char * out)
References fat_item::item, fat_file_descriptor::item, and fat_file_descriptor::pos.
fat16_resolve()
int fat16_resolve (struct disk * disk)
References ALL_OK, diskstreamer_new(), diskstreamer_read(), EIO, ENOMEM, fat_header::fat_header_extended::extended, fat16_fs, fat16_init_private(), disk::filesystem, disk::fs_private, fat_private::header, disk::id, kernel_debug(), kzalloc(), fat_header::shared, and fat16_header_extended::signature.
Variable Documentation
fat16_fs
struct filesystem fat16_fs
Initial value:
=
{
    .resolve = fat16_resolve,
    .open = fat16_open,
    .read = fat16_read
}