GitOS: src/kernel/fs/file.c File Reference
file.c File Reference
#include "file.h"
#include <stdint.h>
#include "kernel.h"
#include "common/string.h"
#include "common/status.h"
#include "memory/memory.h"
#include "memory/heap/kheap.h"
#include "drivers/disk/disk.h"
#include "Path.hpp"
Functions
void fs_insert_filesystem (struct filesystem *filesystem)
Inserts filesystem struct into internal array.
void fs_init ()
Initializes internal filesystem arrays.
struct filesystem * fs_resolve (struct disk *disk)
Resolves filesystem for given disk.
int fopen (const char *filename, const char *str_mode)
Opens file.
int fread (void *ptr, uint32_t size, uint32_t nmemb, int fd)
Reads from file.
int fwrite (void *ptr, uint32_t size, uint32_t nmemb, int fd)
Writes to file.
int fseek (int fd, int offset, FILE_SEEK_MODE whence)
Seeks into file.
int fstat (int fd, struct file_stat *stat)
Returns file status.
int fclose (int fd)
Closes file descriptor.
void mount (const char *filename, struct filesystem *fs, void *data)
Variables
struct filesystem * filesystems [MAX_FILESYSTEMS]
Array holding all registered filesystems.
struct file_descriptor * file_descriptors [MAX_FILEDESCRIPTORS]
Array holding all open file descriptors.
struct mounted_file ** mounted
Array holding all mounted files.
Function Documentation
fclose()
int fclose (int fd)
Closes file descriptor.
Parameters
fd File descriptor
Returns
int Status
References filesystem::close, EIO, file_descriptor::filesystem, and file_descriptor::private_fs_descriptor.
fopen()
int fopen (const char * filename, const char * str_mode)
Opens file.
Parameters
filename File to open
str_mode Open mode
Returns
int Status
References file_descriptor::disk, disk_get(), EINVARG, EIO, FILE_MODE_INVALID, filename, disk::filesystem, file_descriptor::filesystem, mounted_file::fs, disk::fs_private, file_descriptor::index, MAX_MOUNTED, mounted, path_part::next, filesystem::open, pathparser_get_drive_number(), pathparser_parse(), file_descriptor::private_fs_descriptor, and strcmp().
fread()
int fread (void * ptr, uint32_t size, uint32_t nmemb, int fd)
Reads from file.
Parameters
ptr Output buffer
size Size in bytes of block
nmemb Number of blocks to read
fd File descriptor
Returns
int Status
References file_descriptor::disk, EINVARG, file_descriptor::filesystem, disk::fs_private, file_descriptor::private_fs_descriptor, filesystem::read, and size.
fs_init()
void fs_init ()
Initializes internal filesystem arrays.
References file_descriptors, filesystems, kzalloc(), MAX_MOUNTED, memset(), and mounted.
fs_insert_filesystem()
void fs_insert_filesystem (struct filesystem * filesystem)
Inserts filesystem struct into internal array.
Parameters
filesystem
References fs, kernel_panic(), kprintf(), and filesystem::name.
fs_resolve()
struct filesystem * fs_resolve (struct disk * disk)
Resolves filesystem for given disk.
Parameters
disk Disk to resolve
Returns
struct filesystem* Resolved filesystem, 0 if not resolved
References ALL_OK, filesystems, disk::id, kprintf(), MAX_FILESYSTEMS, filesystem::name, and filesystem::resolve.
fseek()
int fseek (int fd, int offset, FILE_SEEK_MODE whence)
Seeks into file.
Parameters
fd File descriptor
offset Seek offset
whence File seek mode (SEEK_SET for absolute, SEEK_CUR for relative)
Returns
int Status
References EIO, file_descriptor::filesystem, offset, file_descriptor::private_fs_descriptor, and filesystem::seek.
fstat()
int fstat (int fd, struct file_stat * stat)
Returns file status.
Parameters
fd File descriptor
stat Output file status struct
Returns
int Status
References EIO, file_descriptor::filesystem, file_descriptor::private_fs_descriptor, and filesystem::stat.
fwrite()
int fwrite (void * ptr, uint32_t size, uint32_t nmemb, int fd)
Writes to file.
Parameters
ptr Input buffer
size Size in bytes of block
nmemb Number of blocks to read
fd File descriptor
Returns
int Status
References file_descriptor::disk, EINVARG, file_descriptor::filesystem, disk::fs_private, file_descriptor::private_fs_descriptor, size, and filesystem::write.
mount()
void mount (const char * filename, struct filesystem * fs, void * data)
References mounted_file::data, filename, mounted_file::filename, mounted_file::fs, fs, kdebug, kernel_panic(), kzalloc(), MAX_MOUNTED, and mounted.
Variable Documentation
file_descriptors
struct file_descriptor* file_descriptors[MAX_FILEDESCRIPTORS]
Array holding all open file descriptors.
filesystems
struct filesystem* filesystems[MAX_FILESYSTEMS]
Array holding all registered filesystems.
mounted
struct mounted_file** mounted
Array holding all mounted files.