GitOS: src/kernel/fs/file.h File Reference
file.h File Reference
#include <stdint.h>
#include "drivers/disk/disk.h"
#include "pathparser.h"
Data Structures
struct file_descriptor
struct file_stat
struct filesystem
Macros
#define MAX_FILESYSTEMS 12
#define MAX_FILEDESCRIPTORS 1024
#define MAX_FILESYSTEM_NAME 20
Typedefs
typedef unsigned int FILE_SEEK_MODE
typedef unsigned int FILE_MODE
typedef unsigned int FILE_STAT_FLAGS
typedef int(* FS_RESOLVE_FUNCTION) (struct disk *disk)
typedef void *(* FS_OPEN_FUNCTION) (void *private, struct path_part *path, FILE_MODE mode)
typedef int(* FS_READ_FUNCTION) (void *private, void *descriptor, uint32_t size, uint32_t nmemb, char *out)
typedef int(* FS_SEEK_FUNCTION) (void *private, uint32_t offset, FILE_SEEK_MODE seek_mode)
typedef int(* FS_STAT_FUNCTION) (void *private, struct file_stat *stat)
typedef int(* FS_CLOSE_FUNCTION) (void *private)
Enumerations
enum FILE_SEEK_MODES { SEEK_SET , SEEK_CUR , SEEK_END }
enum FILE_OPEN_MODES { FILE_MODE_READ , FILE_MODE_WRITE , FILE_MODE_APPEND , FILE_MODE_INVALID }
enum FILE_STAT_FLAGS { FILE_STAT_READ_ONLY = 0b00000001 }
Functions
void fs_init ()
Initializes internal filesystem arrays.
void fs_insert_filesystem (struct filesystem *filesystem)
Inserts filesystem struct into internal array.
struct filesystem * fs_resolve (struct disk *disk)
Resolves filesystem for given disk.
int fopen (const char *filename, const char *mode)
Opens file.
int fread (void *ptr, uint32_t size, uint32_t nmemb, int fd)
Reads from file.
int fseek (int fd, int offset, FILE_SEEK_MODE whence)
Seeks into file.
int fstat (int fd, struct file_stat *stat)
Returns file status.
int fclose (int fd)
Closes file descriptor.
Macro Definition Documentation
MAX_FILEDESCRIPTORS
#define MAX_FILEDESCRIPTORS 1024
MAX_FILESYSTEM_NAME
#define MAX_FILESYSTEM_NAME 20
MAX_FILESYSTEMS
#define MAX_FILESYSTEMS 12
Typedef Documentation
FILE_MODE
typedef unsigned int FILE_MODE
FILE_SEEK_MODE
typedef unsigned int FILE_SEEK_MODE
FILE_STAT_FLAGS
typedef unsigned int FILE_STAT_FLAGS
FS_CLOSE_FUNCTION
typedef int(* FS_CLOSE_FUNCTION) (void *private)
FS_OPEN_FUNCTION
typedef void*(* FS_OPEN_FUNCTION) (void *private, struct path_part *path, FILE_MODE mode)
FS_READ_FUNCTION
typedef int(* FS_READ_FUNCTION) (void *private, void *descriptor, uint32_t size, uint32_t nmemb, char *out)
FS_RESOLVE_FUNCTION
typedef int(* FS_RESOLVE_FUNCTION) (struct disk *disk)
FS_SEEK_FUNCTION
typedef int(* FS_SEEK_FUNCTION) (void *private, uint32_t offset, FILE_SEEK_MODE seek_mode)
FS_STAT_FUNCTION
typedef int(* FS_STAT_FUNCTION) (void *private, struct file_stat *stat)
Enumeration Type Documentation
FILE_OPEN_MODES
enum FILE_OPEN_MODES
Enumerator
FILE_MODE_READ
FILE_MODE_WRITE
FILE_MODE_APPEND
FILE_MODE_INVALID
FILE_SEEK_MODES
enum FILE_SEEK_MODES
Enumerator
SEEK_SET
Absolute position from 0.
SEEK_CUR
Relative position.
SEEK_END
Absolute position from the end of file.
FILE_STAT_FLAGS
enum FILE_STAT_FLAGS
Enumerator
FILE_STAT_READ_ONLY
Function Documentation
fclose()
int fclose (int fd)
Closes file descriptor.
Parameters
fd File descriptor
Returns
int Status
fopen()
int fopen (const char * filename, const char * str_mode)
Opens file.
Parameters
filename File to open
str_mode Open mode
Returns
int Status
References disk_get(), path_root::drive_no, EINVARG, EIO, filename, disk::filesystem, path_root::first, and pathparser_parse().
fread()
int fread (void * ptr, uint32_t size, uint32_t nmemb, int fd)
Reads from file.
Parameters
ptr Output buffer
size Size in bytes of block
nmemb Number of blocks to read
fd File descriptor
Returns
int Status
References EINVARG, and size.
fs_init()
void fs_init ()
Initializes internal filesystem arrays.
References file_descriptors, filesystems, and memset().
fs_insert_filesystem()
void fs_insert_filesystem (struct filesystem * filesystem)
Inserts filesystem struct into internal array.
Parameters
filesystem
References fs, and kernel_panic().
fs_resolve()
struct filesystem* fs_resolve (struct disk * disk)
Resolves filesystem for given disk.
Parameters
disk Disk to resolve
Returns
struct filesystem* Resolved filesystem, 0 if not resolved
References ALL_OK, filesystems, disk::id, kprintf(), MAX_FILESYSTEMS, filesystem::name, and filesystem::resolve.
fseek()
int fseek (int fd, int offset, FILE_SEEK_MODE whence)
Seeks into file.
Parameters
fd File descriptor
offset Seek offset
whence File seek mode (SEEK_SET for absolute, SEEK_CUR for relative)
Returns
int Status
fstat()
int fstat (int fd, struct file_stat * stat)
Returns file status.
Parameters
fd File descriptor
stat Output file status struct
Returns
int Status