GitOS: src/userland/stdlib/graphics/framebuffer.cpp File Reference
framebuffer.cpp File Reference
#include "framebuffer.hpp"
#include <stdint.h>
#include <misc.h>
#include "stdio.h"
#include "string.h"
Functions
void printf (const char *fmt,...)
void puts (const char *str)
void putc (char c)
Function Documentation
printf()
void printf (const char * fmt, ...)
References memset(), FramebufferGraphics::print_string(), FramebufferGraphics::the(), and vsprintf().
putc()
void putc (char c)
References FramebufferGraphics::print_char(), and FramebufferGraphics::the().
puts()
void puts (const char * str)
References FramebufferGraphics::print_string(), and FramebufferGraphics::the().