var hierarchy =
[
    [ "BMPFile", "class_b_m_p_file.html", null ],
    [ "disk", "structdisk.html", null ],
    [ "disk_stream", "structdisk__stream.html", null ],
    [ "ELFFile", "class_e_l_f_file.html", null ],
    [ "fat16_header_extended", "structfat16__header__extended.html", null ],
    [ "fat16_header_primary", "structfat16__header__primary.html", null ],
    [ "fat_directory", "structfat__directory.html", null ],
    [ "fat_file", "structfat__file.html", null ],
    [ "fat_file_descriptor", "structfat__file__descriptor.html", null ],
    [ "fat_header", "structfat__header.html", null ],
    [ "fat_header_extended", "unionfat__header_1_1fat__header__extended.html", null ],
    [ "fat_item", "structfat__item.html", null ],
    [ "fat_private", "structfat__private.html", null ],
    [ "file_descriptor", "structfile__descriptor.html", null ],
    [ "file_stat", "structfile__stat.html", null ],
    [ "filesystem", "structfilesystem.html", null ],
    [ "FramebufferGraphics", "class_framebuffer_graphics.html", null ],
    [ "FramebufferInfo", "struct_framebuffer_info.html", null ],
    [ "gdt", "structgdt.html", null ],
    [ "gdt_descriptor", "structgdt__descriptor.html", null ],
    [ "gdt_structured", "structgdt__structured.html", null ],
    [ "Graphics", "class_graphics.html", [
      [ "TextModeGraphics", "class_text_mode_graphics.html", null ],
      [ "VBEGraphics", "class_v_b_e_graphics.html", null ]
    ] ],
    [ "heap", "structheap.html", null ],
    [ "heap_table", "structheap__table.html", null ],
    [ "idt_desc", "structidt__desc.html", null ],
    [ "idtr_desc", "structidtr__desc.html", null ],
    [ "interrupt_frame", "structinterrupt__frame.html", null ],
    [ "keyboard_buffer", "structprocess_1_1keyboard__buffer.html", null ],
    [ "MemoryFS", "class_memory_f_s.html", null ],
    [ "mounted_file", "structmounted__file.html", null ],
    [ "mouse_packet", "structmouse__packet.html", null ],
    [ "mouse_packet", "struct_p_s2_mouse_1_1mouse__packet.html", null ],
    [ "paging_chunk", "structpaging__chunk.html", null ],
    [ "path_part", "structpath__part.html", null ],
    [ "path_root", "structpath__root.html", null ],
    [ "PipeFS", "class_pipe_f_s.html", null ],
    [ "process", "structprocess.html", null ],
    [ "PS2Mouse", "class_p_s2_mouse.html", null ],
    [ "registers", "structregisters.html", null ],
    [ "task", "structtask.html", null ],
    [ "tss", "structtss.html", null ]
];