GitOS: src/kernel/kernel.cpp File Reference
kernel.cpp File Reference
#include "kernel.h"
#include "drivers/graphics/graphics.hpp"
#include "drivers/graphics/vbe/vbe_graphics.hpp"
#include "drivers/graphics/text_mode/text_mode.hpp"
#include "syscall/syscall.hpp"
#include <stdint.h>
#include <stdarg.h>
#include "idt/idt.h"
#include "drivers/serial/serial.h"
#include "drivers/pic/pic.h"
#include "memory/bios_memory_map.h"
#include "memory/heap/kheap.h"
#include "memory/memory.h"
#include "common/io.h"
#include "common/status.h"
#include "common/string.h"
#include "memory/paging/paging.h"
#include "drivers/disk/disk.h"
#include "drivers/disk/disk_streamer.h"
#include "fs/pathparser.h"
#include "fs/file.h"
#include "fs/fat16/fat16.h"
#include "gdt/gdt.h"
#include "task/tss.h"
#include "task/task.h"
#include "task/process.h"
#include "drivers/ps2keyboard/ps2keyboard.h"
Functions
int atexit (void(*)())
void * operator new (size_t size)
void * operator new[] (size_t size)
void operator delete (void *p)
void operator delete[] (void *p)
void print_interrupt_frame (struct interrupt_frame *frame)
void timer_interrupt (int int_no, struct interrupt_frame *frame)
Temporary PIC Timer interrupt handler.
void kernel_exception (int int_no, struct interrupt_frame *frame)
void kernel_page ()
void kernel_main ()
Kernel C entry point.
void kernel_panic (const char *fmt,...)
(Temporary) Prints kernel_message and halts the kernel.
void kernel_halt ()
void kprintf (const char *fmt,...)
Prints to kernel debug channels. Max length of processed message is 1024 characters.
void __cxa_pure_virtual ()
Variables
struct tss tss
struct gdt gdt_real [TOTAL_GDT_SEGMENTS]
struct gdt_structured gdt_structured [TOTAL_GDT_SEGMENTS]
Function Documentation
__cxa_pure_virtual()
void __cxa_pure_virtual ()
References kernel_panic().
atexit()
int atexit (void(*)())
kernel_exception()
void kernel_exception (int int_no, struct interrupt_frame * frame)
References COM1, interrupt_frame::cs, ebp, interrupt_frame::ebp, filename, Graphics::GREY, idt_InterruptLayoutString, kprintf(), ksprintf(), Graphics::LIGHT_RED, memset(), print_interrupt_frame(), Graphics::print_string(), process_current(), process_terminate(), ser_PrintString(), Graphics::set_text_color(), task_current(), task_return(), and task_switch().
kernel_halt()
void kernel_halt ()
kernel_main()
void kernel_main ()
Kernel C entry point.
References process::argc, process::argv, bios_memory_map, Graphics::clear_screen(), COM1, disk_search_and_init(), tss::esp0, fat16_init_filesystem(), fs_init(), fs_insert_filesystem(), gdt_load(), gdt_read(), gdt_real, gdt_structured_to_gdt(), Graphics::GREY, idt_Init(), idt_Load(), idt_SetDescriptor(), idt_SetHandler(), kdebug, KERNEL_DATA_SELECTOR, kernel_exception(), kernel_panic(), kheap_init(), kprintf(), memcmp(), memory_map_entry, memset(), PAGING_ACCESS_FROM_ALL, paging_align_address(), paging_enable(), PAGING_IS_PRESENT, PAGING_IS_WRITEABLE, paging_map_to(), paging_new_directory(), paging_switch(), pic_Remap(), process_load_switch(), ps2keyboard_setup(), ser_Init(), Graphics::set_text_color(), tss::ss0, gdt_descriptor::start_address, syscall_init(), syscall_wrapper(), task_run_first_ever_task(), timer_interrupt(), TOTAL_GDT_SEGMENTS, and tss_load().
kernel_page()
void kernel_page ()
References kernel_registers(), and paging_switch().
kernel_panic()
void kernel_panic (const char * fmt, ...)
(Temporary) Prints kernel_message and halts the kernel.
Parameters
fmt Reason of the panic
... Arguments
References COM1, kernel_halt(), kvsprintf(), Graphics::LIGHT_RED, memset(), Graphics::print_string_color(), and ser_PrintString().
kprintf()
void kprintf (const char * fmt, ...)
Prints to kernel debug channels. Max length of processed message is 1024 characters.
Parameters
fmt Message to format and print.
... Arguments
References COM1, kvsprintf(), memset(), Graphics::print_string(), and ser_PrintString().
operator delete()
void operator delete (void * p)
References kfree().
operator delete[]()
void operator delete[] (void * p)
References kfree().
operator new()
void * operator new (size_t size)
References kzalloc(), and size.
operator new[]()
void * operator new[] (size_t size)
References kzalloc(), and size.
print_interrupt_frame()
void print_interrupt_frame (struct interrupt_frame * frame)
References interrupt_frame::cs, interrupt_frame::eax, interrupt_frame::ebp, interrupt_frame::ebx, interrupt_frame::ecx, interrupt_frame::edi, interrupt_frame::edx, interrupt_frame::error_code, interrupt_frame::esi, interrupt_frame::esp, interrupt_frame::flags, interrupt_frame::ip, kprintf(), and interrupt_frame::ss.
timer_interrupt()
void timer_interrupt (int int_no, struct interrupt_frame * frame)
Temporary PIC Timer interrupt handler.
Parameters
frame Interrupt frame
References pic_EOI().
Variable Documentation
gdt_real
struct gdt gdt_real[TOTAL_GDT_SEGMENTS]
gdt_structured
struct gdt_structured gdt_structured[TOTAL_GDT_SEGMENTS]
Initial value:
= {
    {.base = 0x00, .limit = 0x00, .type = 0x00},
    {.base = 0x00, .limit = 0xFFFFFFFF, .type = 0x9A},
    {.base = 0x00, .limit = 0xFFFFFFFF, .type = 0x92},
    {.base = 0x00, .limit = 0xFFFFFFFF, .type = 0xF8},
    {.base = 0x00, .limit = 0xFFFFFFFF, .type = 0xF2},
    {.base = (uint32_t)&tss, .limit = sizeof(tss), .type = 0xE9},
}
tss
struct tss tss