GitOS: src/kernel/kernel.c File Reference
kernel.c File Reference
#include "kernel.h"
#include <stdint.h>
#include "idt/idt.h"
#include "drivers/text_mode/text_mode.h"
#include "drivers/serial/serial.h"
#include "drivers/pic/pic.h"
#include "common/string.h"
#include "memory/bios_memory_map.h"
#include "memory/heap/kheap.h"
#include "memory/memory.h"
#include "common/io.h"
#include "memory/paging/paging.h"
Functions
void divide_by_zero ()
Temporary int 0x0 handler.
void int21h ()
Located in idt_handler.asm entry point for interrupt 0x0.
void int21h_handler ()
Temporary int 0x21 handler.
void kernel_main ()
Kernel C entry point.
void kernel_panic (char *message)
(Temporary) Prints kernel_message and halts the kernel.
void kernel_halt ()
void kernel_message (char *message, enum TEXT_MODE_COLORS col)
Prints message onto Framebuffer and Serial.
Function Documentation
divide_by_zero()
void divide_by_zero ()
Temporary int 0x0 handler.
References kernel_panic().
int21h()
void int21h ()
Located in idt_handler.asm entry point for interrupt 0x0.
int21h_handler()
void int21h_handler ()
Temporary int 0x21 handler.
References inb(), pic_EOI(), and tm_PrintChar().
kernel_halt()
void kernel_halt ()
kernel_main()
void kernel_main ()
Kernel C entry point.
References bios_memory_map, COM1, CYAN, divide_by_zero(), GREY, idt_Init(), idt_Load(), idt_SetDescriptor(), int21h(), kernel_message(), kernel_panic(), kheap_init(), ksprintf(), LIGHT_GREEN, memory_map_entry, memset(), ser_Init(), tm_ClearScreen(), tm_SetColor(), and YELLOW.
kernel_message()
void kernel_message (char * message, enum TEXT_MODE_COLORS col)
Prints message onto Framebuffer and Serial.
Parameters
message Message
col Color
References COM1, ser_PrintString(), tm_GetColor(), tm_PrintString(), and tm_SetColor().
kernel_panic()
void kernel_panic (char * message)
(Temporary) Prints kernel_message and halts the kernel.
Parameters
message Reason of the panic
References kernel_halt(), kernel_message(), and LIGHT_RED.