GitOS: src/kernel/memory/heap/kheap.h File Reference
kheap.h File Reference
#include <stddef.h>
#include <stdint.h>
Functions
int kheap_init (void *start_address, uint32_t size)
Initializes kernel heap.
void * kmalloc (size_t size)
Allocates specified size in heap.
void * kzalloc (size_t size)
Allocated specified size in heap and zeroes it.
void kfree (void *ptr)
Frees specified pointer.
Function Documentation
kfree()
void kfree (void * ptr)
Frees specified pointer.
Parameters
ptr Pointer to free
References heap_free(), and kernel_heap.
kheap_init()
int kheap_init (void * start_address, uint32_t size)
Initializes kernel heap.
Parameters
start_address Starting address for heap allocation
size Size of heap in bytes
Returns
int Status
References heap_table::entries, HEAP_BLOCK_SIZE, heap_create(), HEAP_TABLE_ADDRESS, kernel_heap, kernel_heap_table, and heap_table::total.
kmalloc()
void* kmalloc (size_t size)
Allocates specified size in heap.
Parameters
size Requested allocation size
Returns
void* Pointer to allocated memory, 0 if errored
References heap_malloc(), and kernel_heap.
kzalloc()
void* kzalloc (size_t size)
Allocated specified size in heap and zeroes it.
Parameters
size Requested allocation swize
Returns
void* Pointer to allocated memory, 0 if errored
References kmalloc(), and memset().