GitOS: src/kernel/fs/pathparser.c File Reference
pathparser.c File Reference
#include "pathparser.h"
#include <stdbool.h>
#include "common/string.h"
#include "common/status.h"
#include "memory/heap/kheap.h"
#include "memory/memory.h"
Functions
struct path_part * pathparset_parse_path_part (struct path_part *last_part, const char **path)
void pathparser_free (struct path_root *root)
int pathparser_parse (struct path_root **path_root_out, const char *path, const char *current_dir_path)
Function Documentation
pathparser_free()
void pathparser_free (struct path_root * root)
References path_root::first, kfree(), path_part::next, and path_part::part.
pathparser_parse()
int pathparser_parse (struct path_root ** path_root_out, const char * path, const char * current_dir_path)
References drive_number, EINVARG, ENOMEM, MAX_PATH, path_part::part, pathparset_parse_path_part(), and strlen().
pathparset_parse_path_part()
struct path_part * pathparset_parse_path_part (struct path_part * last_part, const char ** path)
References kzalloc(), path_part::next, and path_part::part.