GitOS: src/kernel/task/process.h File Reference
process.h File Reference
#include <stdint.h>
#include "fs/pathparser.h"
Data Structures
struct process
struct process::keyboard_buffer
Macros
#define PROGRAM_MAX_ALLOCATIONS 1024
#define PROCESS_KEYBOARD_BUFFER_SIZE 1024
#define MAX_PROCESSES 12
Functions
int process_load_switch (const char *filename, struct process **process)
int process_load (const char *filename, struct process **process)
struct process * process_current ()
int process_switch (struct process *process)
void process_pushkey (struct process *process, char c)
char process_popkey (struct process *process)
Macro Definition Documentation
MAX_PROCESSES
#define MAX_PROCESSES 12
PROCESS_KEYBOARD_BUFFER_SIZE
#define PROCESS_KEYBOARD_BUFFER_SIZE 1024
PROGRAM_MAX_ALLOCATIONS
#define PROGRAM_MAX_ALLOCATIONS 1024
Function Documentation
process_current()
struct process * process_current ()
References current_process.
process_load()
int process_load (const char * filename, struct process ** process)
References EISTKN, filename, process_get_free_slot(), and process_load_for_slot().
process_load_switch()
int process_load_switch (const char * filename, struct process ** process)
References filename, process_load(), and process_switch().
process_popkey()
char process_popkey (struct process * process)
References process::keyboard_buffer::buffer, process::keyboard_buffer::head, process::keyboard, and task_current().
process_pushkey()
void process_pushkey (struct process * process, char c)
References process::keyboard_buffer::buffer, process::keyboard, and process::keyboard_buffer::tail.
process_switch()
int process_switch (struct process * process)
References current_process.