GitOS: src/kernel/task/process.c File Reference
process.c File Reference
#include "process.h"
#include "memory/memory.h"
#include "memory/heap/kheap.h"
#include "fs/file.h"
#include "common/status.h"
#include "task.h"
#include "common/string.h"
Functions
struct process * process_current ()
struct process * process_get (int process_id)
int process_map_binary (struct process *process)
int process_map_memory (struct process *process)
int process_get_free_slot ()
int process_load_for_slot (const char *filename, struct process **process, int process_slot)
int process_load (const char *filename, struct process **process)
Variables
struct process * current_process = 0
Function Documentation
process_current()
struct process* process_current ()
References current_process.
process_get()
struct process* process_get (int process_id)
References MAX_PROCESSES.
process_get_free_slot()
int process_get_free_slot ()
References MAX_PROCESSES.
process_load()
int process_load (const char * filename, struct process ** process)
References EISTKN, filename, process_get_free_slot(), and process_load_for_slot().
process_load_for_slot()
int process_load_for_slot (const char * filename, struct process ** process, int process_slot)
References EISTKN, ENOMEM, kzalloc(), and process_get().
process_map_binary()
int process_map_binary (struct process * process)
References task::page_directory, PAGING_ACCESS_FROM_ALL, paging_align_address(), PAGING_IS_PRESENT, PAGING_IS_WRITEABLE, paging_map_to(), PROGRAM_VIRTUAL_ADDRESS, PROGRAM_VIRTUAL_STACK_ADDRESS_END, PROGRAM_VIRTUAL_STACK_SIZE, process::ptr, process::size, process::stack, and process::task.
process_map_memory()
int process_map_memory (struct process * process)
References process_map_binary().
Variable Documentation
current_process
struct process* current_process = 0