GitOS: src/kernel/task/process.cpp File Reference
process.cpp File Reference
#include "process.h"
#include "memory/memory.h"
#include "memory/heap/kheap.h"
#include "memory/paging/paging.h"
#include "fs/file.h"
#include "common/status.h"
#include "task.h"
#include "common/string.h"
#include "kernel.h"
#include "formats/elf/ELFFile.hpp"
Functions
struct process * process_current ()
struct process * process_get (int process_id)
int process_switch (struct process *process)
int elf_load (const char *filename, ELFFile **elf_file)
int process_map_memory (struct process *process)
int process_get_free_slot ()
int process_load_switch (const char *filename, struct process *process)
int process_load_for_slot (const char *filename, struct process *process, int process_slot)
int process_load (const char *filename, struct process *process)
void process_pushkey (struct process *process, char c)
char process_popkey (struct process *process)
int process_get_next_allocation_index (struct process *process)
void * process_malloc (struct process *process, size_t size)
void process_free (struct process *process, void *address)
void process_terminate (struct process *process)
Variables
struct process * current_process = 0
Function Documentation
elf_load()
int elf_load (const char * filename, ELFFile ** elf_file)
References fclose(), filename, file_stat::filesize, fopen(), fread(), fstat(), and kzalloc().
process_current()
struct process * process_current ()
References current_process.
process_free()
void process_free (struct process * process, void * address)
References process::allocations, kfree(), and PROCESS_MAX_ALLOCATIONS.
process_get()
struct process * process_get (int process_id)
References MAX_PROCESSES.
process_get_free_slot()
int process_get_free_slot ()
References EISTKN, and MAX_PROCESSES.
process_get_next_allocation_index()
int process_get_next_allocation_index (struct process * process)
References process::allocations, ENOMEM, and PROCESS_MAX_ALLOCATIONS.
process_load()
int process_load (const char * filename, struct process * process)
References EISTKN, filename, process_get_free_slot(), and process_load_for_slot().
process_load_for_slot()
int process_load_for_slot (const char * filename, struct process * process, int process_slot)
References EISTKN, process::elf, ENOMEM, ERROR_I, filename, process::filename, process::id, ISERR, kzalloc(), task::process, process_get(), process_map_memory(), PROGRAM_VIRTUAL_STACK_SIZE, process::stack, strncpy(), process::task, task_free(), and task_new().
process_load_switch()
int process_load_switch (const char * filename, struct process * process)
References filename, process_load(), and process_switch().
process_malloc()
void * process_malloc (struct process * process, size_t size)
References process::allocations, ENOMEM, kfree(), kmalloc(), task::page_directory, PAGING_ACCESS_FROM_ALL, paging_align_address(), PAGING_IS_PRESENT, PAGING_IS_WRITEABLE, paging_map_to(), process_get_next_allocation_index(), size, and process::task.
process_map_memory()
int process_map_memory (struct process * process)
References process::elf, ELFFile::get_header(), ELFFile::get_program_header(), task::page_directory, PAGING_ACCESS_FROM_ALL, paging_align_address(), paging_align_address_to_lower_page(), PAGING_IS_PRESENT, PAGING_IS_WRITEABLE, paging_map_to(), ELFFile::PF_W, PROGRAM_VIRTUAL_STACK_ADDRESS_END, PROGRAM_VIRTUAL_STACK_SIZE, process::stack, and process::task.
process_popkey()
char process_popkey (struct process * process)
References process::keyboard_buffer::buffer, process::keyboard_buffer::head, process::keyboard, and task_current().
process_pushkey()
void process_pushkey (struct process * process, char c)
References process::keyboard_buffer::buffer, process::keyboard, and process::keyboard_buffer::tail.
process_switch()
int process_switch (struct process * process)
References current_process.
process_terminate()
void process_terminate (struct process * process)
References process::allocations, current_process, process::elf, kernel_panic(), kfree(), MAX_PROCESSES, task::process, PROCESS_MAX_ALLOCATIONS, process_switch(), process::stack, process::task, and task_free().
Variable Documentation
current_process
struct process* current_process = 0