GitOS: src/kernel/drivers/ps2keyboard/ps2keyboard.c File Reference
ps2keyboard.c File Reference
#include "ps2keyboard.h"
#include <stdint.h>
#include <stddef.h>
#include "keyboard/keyboard.h"
#include "common/io.h"
#include "kernel.h"
#include "idt/idt.h"
#include "task/task.h"
#include "drivers/pic/pic.h"
Functions
int ps2keyboard_setup ()
struct keyboard * ps2keyboard_init ()
void ps2keyboard_irq_handler ()
Variables
struct keyboard ps2keyboard
Function Documentation
ps2keyboard_init()
struct keyboard* ps2keyboard_init ()
References ps2keyboard.
ps2keyboard_irq_handler()
void ps2keyboard_irq_handler ()
References inb(), kernel_page(), and pic_EOI().
ps2keyboard_setup()
int ps2keyboard_setup ()
References idt_SetHandler(), kprintf(), outb(), and ps2keyboard_irq_handler().
Variable Documentation
ps2keyboard
struct keyboard ps2keyboard
Initial value:
= {
    .name = "PS2 Keyboard",
    .init = ps2keyboard_setup
}