GitOS: src/kernel/drivers/ps2keyboard/ps2keyboard.h File Reference
ps2keyboard.h File Reference
Functions
int ps2keyboard_setup ()
Function Documentation
ps2keyboard_setup()
int ps2keyboard_setup ()
References idt_SetHandler(), kprintf(), outb(), and ps2keyboard_irq_handler().