GitOS: src/userland/shell/shell.cpp File Reference
shell.cpp File Reference
#include <format/bmp/BMPFile.hpp>
#include <graphics/framebuffer.hpp>
#include "../../kernel/kernel.h"
#include "stdio.h"
#include "string.h"
#include "misc.h"
#include "file.h"
Data Structures
struct mouse_packet
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References fopen(), fread(), fseek(), fstat(), fwrite(), malloc(), SEEK_SET, and FramebufferGraphics::the().