GitOS: src/userland/stdlib/stdio.h File Reference
stdio.h File Reference
Functions
void putc (char c)
void puts (const char *s)
void printf (const char *fmt,...)
int getc ()
void debug_putc (char c)
void debug_puts (const char *s)
Function Documentation
debug_putc()
void debug_putc (char c)
debug_puts()
void debug_puts (const char * s)
getc()
int getc ()
printf()
void printf (const char * fmt, ...)
References memset(), FramebufferGraphics::print_string(), FramebufferGraphics::the(), and vsprintf().
putc()
void putc (char c)
References FramebufferGraphics::print_char(), and FramebufferGraphics::the().
puts()
void puts (const char * s)
References FramebufferGraphics::print_string(), and FramebufferGraphics::the().