GitOS: src/kernel/syscall/syscall.cpp File Reference
syscall.cpp File Reference
#include "syscall.hpp"
#include <drivers/graphics/vbe/vbe_graphics.hpp>
#include <fs/file.h>
#include <common/assert.h>
#include <common/string.h>
#include "memory/heap/kheap.h"
#include "idt/idt.h"
#include "kernel.h"
#include "task/task.h"
#include "task/process.h"
Data Structures
struct FramebufferInfo
Functions
void * syscall_handler (int syscall_id, struct interrupt_frame *frame)
void * sys$putstring (struct interrupt_frame *frame)
void * sys$getchar (struct interrupt_frame *frame)
void * sys$putchar (struct interrupt_frame *frame)
void * sys$execprocess (struct interrupt_frame *frame)
void * sys$get_process_arguments (struct interrupt_frame *frame)
void * sys$malloc (struct interrupt_frame *frame)
void * sys$free (struct interrupt_frame *frame)
void * sys$exit (struct interrupt_frame *frame)
void * sys$get_framebuffer_info (struct interrupt_frame *frame)
void * sys$fopen (struct interrupt_frame *frame)
void * sys$fclose (struct interrupt_frame *frame)
void * sys$fread (struct interrupt_frame *frame)
void * sys$fwrite (struct interrupt_frame *frame)
void * sys$fstat (struct interrupt_frame *frame)
void * sys$fseek (struct interrupt_frame *frame)
void syscall_init ()
Function Documentation
sys$execprocess()
void * sys$execprocess (struct interrupt_frame * frame)
References kfree(), MAX_PATH, process_load_switch(), task::registers, process::task, task_copy_string_from(), task_current(), task_peek_stack(), task_return(), and task_switch().
sys$exit()
void * sys$exit (struct interrupt_frame * frame)
References filename, kprintf(), process_current(), process_terminate(), task_current(), task_peek_stack(), task_return(), and task_switch().
sys$fclose()
void * sys$fclose (struct interrupt_frame * frame)
References fclose(), task_current(), and task_peek_stack().
sys$fopen()
void * sys$fopen (struct interrupt_frame * frame)
References fopen(), MAX_PATH, task_copy_string_from(), task_current(), and task_peek_stack().
sys$fread()
void * sys$fread (struct interrupt_frame * frame)
References fread(), size, task_current(), and task_peek_stack().
sys$free()
void * sys$free (struct interrupt_frame * frame)
References task::process, process_free(), task_current(), and task_peek_stack().
sys$fseek()
void * sys$fseek (struct interrupt_frame * frame)
References fseek(), task_current(), and task_peek_stack().
sys$fstat()
void * sys$fstat (struct interrupt_frame * frame)
References file_stat::filesize, file_stat::flags, fstat(), kernel_page(), task_current(), task_page(), and task_peek_stack().
sys$fwrite()
void * sys$fwrite (struct interrupt_frame * frame)
References fwrite(), size, task_current(), and task_peek_stack().
sys$get_framebuffer_info()
void * sys$get_framebuffer_info (struct interrupt_frame * frame)
References bpp, FramebufferInfo::bpp, FramebufferInfo::buffer, framebuffer, process::framebuffer, FramebufferInfo::height, kernel_page(), task::process, task_current(), task_page(), task_peek_stack(), VBEGraphics::the(), and FramebufferInfo::width.
sys$get_process_arguments()
void * sys$get_process_arguments (struct interrupt_frame * frame)
References process::argc, process::argv, kernel_page(), task::process, process_malloc(), strcpy(), strlen(), task_current(), task_page(), and task_peek_stack().
sys$getchar()
void * sys$getchar (struct interrupt_frame * frame)
References process_popkey(), and task_current().
sys$malloc()
void * sys$malloc (struct interrupt_frame * frame)
References task::process, process_malloc(), task_current(), and task_peek_stack().
sys$putchar()
void * sys$putchar (struct interrupt_frame * frame)
References kprintf(), task_current(), and task_peek_stack().
sys$putstring()
void * sys$putstring (struct interrupt_frame * frame)
References kprintf(), task_copy_string_from(), task_current(), and task_peek_stack().
syscall_handler()
void * syscall_handler (int syscall_id, struct interrupt_frame * frame)
References kernel_page(), task_current_save_state(), and task_page().
syscall_init()
void syscall_init ()
References sys$execprocess(), sys$exit(), sys$fclose(), sys$fopen(), sys$fread(), sys$free(), sys$fseek(), sys$fstat(), sys$fwrite(), sys$get_framebuffer_info(), sys$get_process_arguments(), sys$getchar(), sys$malloc(), sys$putchar(), sys$putstring(), SYSCALL_EXECPROCESS, SYSCALL_EXIT, SYSCALL_FCLOSE, SYSCALL_FOPEN, SYSCALL_FREAD, SYSCALL_FREE, SYSCALL_FSEEK, SYSCALL_FSTAT, SYSCALL_FWRITE, SYSCALL_GET_FRAMEBUFFER_INFO, SYSCALL_GET_PROCESS_ARGUMENTS, SYSCALL_GETCHAR, SYSCALL_MALLOC, SYSCALL_PUTCHAR, and SYSCALL_PUTSTRING.