GitOS: src/kernel/syscall/syscall.c File Reference
syscall.c File Reference
#include "syscall.h"
#include "memory/heap/kheap.h"
#include "idt/idt.h"
#include "kernel.h"
#include "task/task.h"
#include "task/process.h"
Functions
void * syscall_handler (int syscall_id, struct interrupt_frame *frame)
void * sys$putstring (struct interrupt_frame *frame)
void * sys$getchar (struct interrupt_frame *frame)
void * sys$putchar (struct interrupt_frame *frame)
void * sys$execprocess (struct interrupt_frame *frame)
void syscall_init ()
Function Documentation
sys$execprocess()
void * sys$execprocess (struct interrupt_frame * frame)
References kfree(), kmalloc(), MAX_PATH, process_load_switch(), task::registers, process::task, task_copy_string_from(), task_current(), task_peek_stack(), task_return(), and task_switch().
sys$getchar()
void * sys$getchar (struct interrupt_frame * frame)
References process_popkey(), and task_current().
sys$putchar()
void * sys$putchar (struct interrupt_frame * frame)
References kprintf(), task_current(), and task_peek_stack().
sys$putstring()
void * sys$putstring (struct interrupt_frame * frame)
References kprintf(), task_copy_string_from(), task_current(), and task_peek_stack().
syscall_handler()
void * syscall_handler (int syscall_id, struct interrupt_frame * frame)
References kernel_page(), task_current_save_state(), and task_page().
syscall_init()
void syscall_init ()
References sys$execprocess(), sys$getchar(), sys$putchar(), sys$putstring(), SYSCALL_EXECPROCESS, SYSCALL_GETCHAR, SYSCALL_PUTCHAR, and SYSCALL_PUTSTRING.