GitOS: src/kernel/drivers/text_mode/text_mode.h File Reference
text_mode.h File Reference
Macros
#define TEXT_MODE_WIDTH 80
#define TEXT_MODE_HEIGHT 25
Enumerations
enum TEXT_MODE_COLORS {
BLACK, BLUE, GREEN, CYAN,
RED, PURPLE, BROWN, GREY,
DARK_GREY, LIGHT_BLUE, LIGHT_GREEN, LIGHT_CYAN,
LIGHT_RED, LIGHT_PURPLE, YELLOW, WHITE
}
Functions
void tm_PrintChar (char c)
Prints char to screen.
void tm_PrintCharColor (char c, enum TEXT_MODE_COLORS fg)
Prints char to screen with specified color.
void tm_PrintString (const char *str)
Prints string to screen.
void tm_PrintStringColor (const char *str, enum TEXT_MODE_COLORS fg)
Prints string to screen with specified color.
void tm_ClearScreen ()
Clears screen.
void tm_ScrollScreen (int amount)
Scrolls framebuffer.
void tm_SetCursor (int new_x, int new_y)
Sets framebuffer cursor to specified values.
void tm_SetColor (enum TEXT_MODE_COLORS col)
Sets new framebuffer color to print.
int tm_GetColor ()
int tm_GetX ()
int tm_GetY ()
Macro Definition Documentation
TEXT_MODE_HEIGHT
#define TEXT_MODE_HEIGHT 25
TEXT_MODE_WIDTH
#define TEXT_MODE_WIDTH 80
Enumeration Type Documentation
TEXT_MODE_COLORS
enum TEXT_MODE_COLORS
Enumerator
BLACK
BLUE
GREEN
CYAN
RED
PURPLE
BROWN
GREY
DARK_GREY
LIGHT_BLUE
LIGHT_GREEN
LIGHT_CYAN
LIGHT_RED
LIGHT_PURPLE
YELLOW
WHITE
Function Documentation
tm_ClearScreen()
void tm_ClearScreen ()
Clears screen.
References memset().
tm_GetColor()
int tm_GetColor ()
Returns
TEXT_MODE_COLORS Current color
tm_GetX()
int tm_GetX ()
Returns
int X
tm_GetY()
int tm_GetY ()
Returns
int Y
tm_PrintChar()
void tm_PrintChar (char c)
Prints char to screen.
Parameters
c Character to print
References tm_PrintCharColor().
tm_PrintCharColor()
void tm_PrintCharColor (char c, enum TEXT_MODE_COLORS fg)
Prints char to screen with specified color.
Parameters
c Character to print
fg Color
tm_PrintString()
void tm_PrintString (const char * str)
Prints string to screen.
Parameters
str String to print
References tm_PrintStringColor().
tm_PrintStringColor()
void tm_PrintStringColor (const char * str, enum TEXT_MODE_COLORS col)
Prints string to screen with specified color.
Parameters
str String to print
col Color
References strlen(), and tm_PrintCharColor().
tm_ScrollScreen()
void tm_ScrollScreen (int amount)
Scrolls framebuffer.
Parameters
amount Amount of lines to scroll
References memcpy().
tm_SetColor()
void tm_SetColor (enum TEXT_MODE_COLORS new_fg)
Sets new framebuffer color to print.
Parameters
new_fg New color to be set
tm_SetCursor()
void tm_SetCursor (int new_x, int new_y)
Sets framebuffer cursor to specified values.
Parameters
new_x X to be set
new_y Y to be set