GitOS: src/userland/stdlib/string.c File Reference
string.c File Reference
#include "string.h"
#include "stdio.h"
#include <stddef.h>
#include <stdarg.h>
Functions
size_t strlen (const char *str)
Determine the length of a string.
size_t strnlen (const char *str, size_t max_len)
Determine the length of a fixed-size string.
char * strrev (char *str)
Reverses string.
char * strcpy (char *dest, const char *src)
Copies string.
char * strncpy (char *dest, const char *src, int n)
Copies string with maximum length.
int strncmp (const char *str1, const char *str2, int n)
Compares two strings with maximum length.
char tolower (char c)
Converts ASCII letter to lowercase.
int istrncmp (const char *str1, const char *str2, int n)
int strnlen_terminator (const char *str, int max, char terminator)
Calculates string length with custom terminator.
char * itoa (long num, char *str, int base)
Converts signed number to string.
char * uitoa (unsigned long num, char *str, int base)
Converts unsigned number to string.
char * vsprintf (char *buf, const char *fmt, va_list args)
Kernel vsprintf params: %% c s p l(mod) d i x.
char * sprintf (char *buf, const char *fmt,...)
Kernel sprintf params: %% c s p l(mod) d i x.
int is_digit (char c)
Determines if given char is an ASCII digit.
int to_numeric_digit (char c)
Converts ASCII digit to numeric.
void * memset (void *ptr, int c, size_t size)
Sets first bytes of memory pointed to specified value.
void * memcpy (void *dstptr, const void *srcptr, size_t size)
Copies memory from one place to another.
int memcmp (void *ptr1, void *ptr2, size_t len)
Compares the first num bytes of the block of memory pointed by ptr1 to the first num bytes pointed by ptr2.
void printf (const char *fmt,...)
Function Documentation
is_digit()
int is_digit (char c)
Determines if given char is an ASCII digit.
Parameters
c Character to test
Returns
int 1 if given char is digit
istrncmp()
int istrncmp (const char * str1, const char * str2, int n)
References tolower().
itoa()
char * itoa (long num, char * str, int base)
Converts signed number to string.
Parameters
num Long to convert
str Buffer
base Base to use when converting the number
Returns
char* Buffer
References base, and strrev().
memcmp()
int memcmp (void * ptr1, void * ptr2, size_t len)
Compares the first num bytes of the block of memory pointed by ptr1 to the first num bytes pointed by ptr2.
Parameters
ptr1 Pointer to block of memory
ptr2 Pointer to block of memory
len Number of bytes to compare
Returns
int
0 if matches,
-1 the first byte that does not match in both memory blocks has a lower value in ptr1 than in ptr2,
1 the first byte that does not match in both memory blocks has a greater value in ptr1 than in ptr2
memcpy()
void * memcpy (void * dstptr, const void * srcptr, size_t size)
Copies memory from one place to another.
Parameters
dstptr Destination pointer
srcptr Source pointer
size Length of copied memory
Returns
void* Destination pointer
References size.
memset()
void * memset (void * ptr, int c, size_t size)
Sets first bytes of memory pointed to specified value.
Parameters
ptr Pointer to the block of memory to fill
c Value to be set
size Number of bytes to set
Returns
void* Pointer to the block of memory
References size.
printf()
void printf (const char * fmt, ...)
References memset(), puts(), and vsprintf().
sprintf()
char * sprintf (char * buf, const char * fmt, ...)
Kernel sprintf params: %% c s p l(mod) d i x.
Parameters
buf Buffer
fmt Text to format
... Args
Returns
char* Buffer
References vsprintf().
strcpy()
char * strcpy (char * dest, const char * src)
Copies string.
Parameters
dest Destination buffer
src Input buffer
Returns
char* Pointer to destination buffer
strlen()
size_t strlen (const char * str)
Determine the length of a string.
Parameters
str String
Returns
size_t Length
strncmp()
int strncmp (const char * str1, const char * str2, int n)
Compares two strings with maximum length.
Parameters
str1 String
str2 String
n Max length
Returns
int 0 -> str1==str2, <0 -> str1<str2, >0 ->str1>str2
strncpy()
char * strncpy (char * dest, const char * src, int n)
Copies string with maximum length.
Parameters
dest Destination buffer
src Input buffer
n Max length
Returns
char* Pointer to destination buffer
strnlen()
size_t strnlen (const char * str, size_t max_len)
Determine the length of a fixed-size string.
Parameters
str
max_len
Returns
size_t
strnlen_terminator()
int strnlen_terminator (const char * str, int max, char terminator)
Calculates string length with custom terminator.
Parameters
str String to measure length
max Max length of string
terminator Custom terminator
Returns
int Length
strrev()
char * strrev (char * str)
Reverses string.
Parameters
str String to reverse
Returns
char* str
References strlen().
to_numeric_digit()
int to_numeric_digit (char c)
Converts ASCII digit to numeric.
Parameters
c ASCII digit
Returns
int Numeric digit
tolower()
char tolower (char c)
Converts ASCII letter to lowercase.
Parameters
c Input letter
Returns
char Lowercase letter
uitoa()
char * uitoa (unsigned long num, char * str, int base)
Converts unsigned number to string.
Parameters
num Unsigned Long to convert
str Buffer
base Base to use when converting the number
Returns
char* Buffer
References base, and strrev().
vsprintf()
char * vsprintf (char * buf, const char * fmt, va_list args)
Kernel vsprintf params: %% c s p l(mod) d i x.
Parameters
buf Buffer
fmt Text to format
va_list arguments
Returns
char* Buffer
References itoa(), memcpy(), memset(), strlen(), and uitoa().