GitOS: src/userland/wintest/wintest.cpp File Reference
wintest.cpp File Reference
#include <stdint-gcc.h>
#include <graphics/framebuffer.hpp>
#include <window/window.h>
#include <file.h>
#include <string.h>
#include <misc.h>
#include <stdio.h>
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
References fopen(), FRAMEBUFFER_DATA, fwrite(), getpid(), malloc(), memcpy(), memset(), window_message_preamble::pid, REGISTER, SET_SIZE, strcpy(), strlen(), and window_message_set_size::width.