GitOS: src/userland/zofia/zofia.cpp File Reference
zofia.cpp File Reference
#include "graphics/framebuffer.hpp"
#include "stdio.h"
#include "string.h"
#include "misc.h"
Functions
const char * get_cwd ()
void process_command (char *str)
int main (int argc, char **argv)
Function Documentation
get_cwd()
const char * get_cwd ()
main()
int main (int argc, char ** argv)
References get_cwd(), getc(), memset(), printf(), process_command(), and putc().
process_command()
void process_command (char * str)
References FramebufferGraphics::clear_screen(), FramebufferGraphics::draw_pixel(), execprocess(), get_cwd(), puts(), strcmp(), strcpy(), strlen(), and FramebufferGraphics::the().